# Generated by Django 4.0.2 on 2022-02-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDName', models.CharField(max_length=100)),
                ('PRDDesc', models.TextField()),
                ('PRDPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PRDCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PRDCreatedAt', models.DateField()),
            ],
        ),
    ]
