# Generated by Django 4.0.2 on 2022-02-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_product_prdcreatedat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PDName',
            new_name='PRDName',
        ),
    ]
