# Generated by Django 4.0.2 on 2022-02-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_product_prdcost_alter_product_prdcreatedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRDImage', models.ImageField(upload_to='products_images/', verbose_name='image ')),
                ('PRDIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product', verbose_name='product id')),
            ],
        ),
    ]
