# Generated by Django 4.0.2 on 2022-02-08 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATName_Category', models.CharField(max_length=50)),
                ('CATDesc', models.TextField()),
                ('CATImage', models.ImageField(upload_to='categories_images/')),
                ('CATParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
    ]
