# Generated by Django 4.0.2 on 2022-02-08 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_product_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='CATDesc',
            field=models.TextField(verbose_name='category desc'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATImage',
            field=models.ImageField(upload_to='categories_images/', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATName_Category',
            field=models.CharField(max_length=50, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='CATParent',
            field=models.ForeignKey(blank=True, limit_choices_to={'CATParent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category', verbose_name='main category'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACAlternatives',
            field=models.ManyToManyField(related_name='accessories_products', to='website.Product', verbose_name='product accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessories',
            name='PACProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='website.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALAlternatives',
            field=models.ManyToManyField(related_name='alternative_products', to='website.Product', verbose_name='product alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='website.product', verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='PRDImage',
            field=models.ImageField(upload_to='products_images/', verbose_name='product image '),
        ),
    ]
