# Generated by Django 4.0.2 on 2022-02-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_product_prdbrand_alter_product_prdcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='product image'),
        ),
    ]
